use super::*;
use jxl_gpu_bitstream::{ColourEncodingInventory, ImageHeaderInventory};
use jxl_gpu_formats::{
    Channel, ChromaLocation2d, ColorModel, ColorRange, ColorSpace, ColorSpec, ColorSpecification,
    Swizzle, TransferFunction, YcbcrEncoding,
};
use jxl_gpu_protocol::{Chromaticity, GammaExponent, RgbChromaticities, icc::IccRenderingIntent};
use jxl_test_support::oracles::icc_profile::IccProfileOracle;
use jxl_wgpu_encode::{
    AnimationHeader, FiniteF16, FrameOptions, FrameTiming, LosslessModularAnimationDescriptor,
    LosslessModularColorOptions,
};

mod lifetime;

fn spaces() -> [ColorSpace; 7] {
    [
        ColorSpace::Bt709,
        ColorSpace::Bt2020,
        ColorSpace::DisplayP3,
        ColorSpace::CustomRgb(RgbChromaticities {
            white: Chromaticity::DCI,
            ..RgbChromaticities::DISPLAY_P3
        }),
        ColorSpace::CustomRgb(RgbChromaticities {
            white: Chromaticity::E,
            ..RgbChromaticities::BT709
        }),
        ColorSpace::CustomRgb(RgbChromaticities {
            white: Chromaticity::new(0.34567, 0.35850).unwrap(),
            ..RgbChromaticities::BT2020
        }),
        ColorSpace::CustomRgb(RgbChromaticities {
            red: Chromaticity::new(0.66, 0.32).unwrap(),
            green: Chromaticity::new(0.24, 0.70).unwrap(),
            blue: Chromaticity::new(0.12, 0.04).unwrap(),
            white: Chromaticity::new(0.32125, 0.33750).unwrap(),
        }),
    ]
}

const INTENTS: [IccRenderingIntent; 4] = [
    IccRenderingIntent::Perceptual,
    IccRenderingIntent::Relative,
    IccRenderingIntent::Saturation,
    IccRenderingIntent::Absolute,
];

fn transfers() -> [TransferFunction; 7] {
    [
        TransferFunction::Linear,
        TransferFunction::Srgb,
        TransferFunction::Bt709,
        TransferFunction::Pq,
        TransferFunction::Hlg,
        TransferFunction::Dci,
        TransferFunction::Gamma(GammaExponent::new(1.0 / 2.2).unwrap()),
    ]
}

fn spec(space: ColorSpace, transfer: TransferFunction) -> ColorSpec {
    ColorSpec {
        space,
        transfer,
        encoding: YcbcrEncoding::Undefined,
        range: ColorRange::Full,
        chroma_location: ChromaLocation2d::CENTER,
    }
}

fn colored(mut source: BufferImageSource, color: ColorSpec) -> BufferImageSource {
    if source.layout.format.model == ColorModel::NonColor {
        source.layout.format.model = ColorModel::Gray;
        source.layout.format.swizzle = Swizzle::X001;
    }
    source.layout.format.color_spec = ColorSpecification::Defined(color);
    source
}

fn header(data: &[u8]) -> ImageHeaderInventory {
    jxl_gpu_bitstream::parse(data, Default::default())
        .unwrap()
        .codestream_inventory(Default::default())
        .unwrap()
        .image_header
}

// Independent public libjxl encoding receives the actual source declaration, not a profile
// generated by the implementation under test. Its original ICC bytes bind every color field.
fn declaration(case: &Case, color: ColorSpec, intent: IccRenderingIntent) -> String {
    let xy = color.space.rgb_space().unwrap().chromaticities().unwrap();
    let white = match xy.white {
        Chromaticity::D65 => 1,
        Chromaticity::E => 10,
        Chromaticity::DCI => 11,
        _ => 2,
    };
    let primaries = match color.space {
        ColorSpace::Bt709 => 1,
        ColorSpace::Bt2020 => 9,
        ColorSpace::DisplayP3 => 11,
        _ => 2,
    };
    let (transfer, gamma) = match color.transfer {
        TransferFunction::Linear => (8, 1.0),
        TransferFunction::Srgb => (13, 0.0),
        TransferFunction::Bt709 => (1, 0.0),
        TransferFunction::Pq => (16, 0.0),
        TransferFunction::Hlg => (18, 0.0),
        TransferFunction::Dci => (17, 0.0),
        TransferFunction::Gamma(value) => (65535, f64::from(value.value())),
        _ => panic!("explicit native test transfer"),
    };
    format!(
        "{} {white} {primaries} {transfer} {} {} {} {} {} {} {} {} {} {gamma}",
        u32::from(case.format == LosslessModularFormat::Gray),
        intent as u32,
        xy.white.x(),
        xy.white.y(),
        xy.red.x(),
        xy.red.y(),
        xy.green.x(),
        xy.green.y(),
        xy.blue.x(),
        xy.blue.y()
    )
}

fn numeric_request(case: &Case, channel: u32) -> GpuOutputRequest {
    let request = if case.kind == SampleKind::Float {
        GpuOutputRequest::numeric(
            PixelFormat::non_color(SampleKind::Float, 32, &[Channel::X]),
            NumericSampleMapping::NativeFloat,
        )
        .unwrap()
    } else {
        GpuOutputRequest::numeric(
            LosslessModularFormat::Gray.pixel_format(case.bits).unwrap(),
            NumericSampleMapping::NativeUnsigned,
        )
        .unwrap()
    };
    if channel == case.format.color_channel_count() {
        request.with_extra_channel(0).unwrap()
    } else {
        request.with_color_channel(channel).unwrap()
    }
}

pub(super) fn check_numeric(rig: &Rig, encoded: &[u8], frames: &[Vec<u32>], case: &Case) {
    let channels = case.format.channel_count() as usize;
    for channel in 0..channels {
        let mut baseline = None;
        for (decoder, fragmented) in rig.decoders.iter().zip([false, true]) {
            let request = numeric_request(case, channel as u32)
                .with_max_frame_slots(std::num::NonZeroUsize::new(frames.len() + 1).unwrap());
            let mut session = if fragmented {
                open_fragmented(decoder, encoded, request)
            } else {
                decoder.open(encoded, request).unwrap()
            };
            let mut retained = Vec::new();
            while let Some(frame) = pollster::block_on(session.next_frame_async()).unwrap() {
                if frames.len() > 1 {
                    let index = retained.len();
                    assert_eq!(frame.metadata.index, index);
                    assert_eq!(frame.metadata.duration.ticks, index as u32 + 2);
                    assert_eq!(frame.metadata.timecode, Some(20 + index as u32));
                    assert_eq!(
                        frame.metadata.presentation_ticks,
                        (0..index as u64).map(|i| i + 2).sum::<u64>()
                    );
                    assert_eq!(frame.metadata.is_last, index + 1 == frames.len());
                }
                retained.push(frame);
            }
            assert_eq!(retained.len(), frames.len());
            drop(session);
            let mut snapshots = Vec::new();
            for (frame, expected) in retained.iter().zip(frames) {
                let actual = read_bytes(&rig.backend, &frame.output().outputs[0]);
                let expected: Vec<_> = expected
                    .iter()
                    .skip(channel)
                    .step_by(channels)
                    .flat_map(|&word| {
                        if case.kind == SampleKind::Float {
                            case.normalized(word).to_bits().to_le_bytes().to_vec()
                        } else {
                            word.to_le_bytes()[..case.bits.next_power_of_two().max(8) as usize / 8]
                                .to_vec()
                        }
                    })
                    .collect();
                assert_eq!(
                    actual, expected,
                    "original GPU {case:?} channel {channel}, fragmented={fragmented}"
                );
                snapshots.push(actual);
            }
            drop(retained);
            assert_eq!(decoder.engine().in_flight_memory_stats().reserved_bytes, 0);
            if let Some(baseline) = &baseline {
                assert_eq!(&snapshots, baseline);
            } else {
                baseline = Some(snapshots);
            }
        }
    }
}

#[test]
fn enumerated_source_colors_preserve_native_profiles_and_exact_gpu_words() {
    let rig = Rig::new();
    let oracle = IccProfileOracle::compile();
    // Reuse the GPU encoders/pipelines for all declarations. The image white is independent
    // of the transfer enum; both SDR and HDR declarations exercise each selected white.
    let encoders: Vec<_> = (0..4)
        .map(|index| {
            LosslessModularEncoder::with_tree_mode(rig.context.clone(), TREES[index % 2])
                .with_color_options(LosslessModularColorOptions {
                    rendering_intent: INTENTS[index],
                    intensity_target: FiniteF16::from_bits([0x5bf8, 0x63d0, 0x70e2, 0x7bff][index])
                        .unwrap(),
                })
                .unwrap()
        })
        .collect();
    for (space_index, space) in spaces().into_iter().enumerate() {
        for (transfer_index, transfer) in transfers().into_iter().enumerate() {
            let index = space_index * 7 + transfer_index;
            let color = spec(space, transfer);
            let (kind, bits) = [
                (SampleKind::Unsigned, 8),
                (SampleKind::Unsigned, 12),
                (SampleKind::Unsigned, 31),
                (SampleKind::Float, 16),
                (SampleKind::Float, 32),
            ][index % 5];
            let case = Case {
                format: [
                    LosslessModularFormat::Gray,
                    LosslessModularFormat::Rgb,
                    LosslessModularFormat::Rgba,
                ][index % 3],
                bits,
                kind,
                storage: [Storage::Packed, Storage::Planar, Storage::Split][(index / 3) % 3],
                reversed: true,
                byte_order: ByteOrder::Big,
                shifted: true,
            };
            let extent = Extent2d::new(257, 3);
            let expected = case.samples(extent);
            let input = colored(upload(&rig.context, &case, extent, &expected, 4099), color);
            let encoder = &encoders[index % 4];
            let encoded = pollster::block_on(encoder.submit_container(input).unwrap()).unwrap();
            let canonical = colored(
                upload(&rig.context, &case.canonical(), extent, &expected, 0),
                color,
            );
            assert_eq!(encoded, encoder.encode_container(canonical).unwrap());
            let native_profile = oracle.create(&declaration(&case, color, INTENTS[index % 4]));
            assert_eq!(
                oracle.read(&encoded).profile,
                native_profile.profile,
                "profile {case:?} {color:?}"
            );
            let image = header(&encoded);
            let mut declaration = header(&native_profile.input).colour_encoding;
            if let TransferFunction::Gamma(gamma) = color.transfer {
                // The native encoder can choose the adjacent gamma code while yielding the
                // same exact ICC bytes (checked above). The writer's wire gamma is required
                // to be the nearest 1e-7 representation of the supplied source exponent.
                let ColourEncodingInventory::Enumerated {
                    transfer_function, ..
                } = &mut declaration
                else {
                    panic!("native enumerated source color");
                };
                *transfer_function = jxl_gpu_bitstream::TransferFunctionInventory::Gamma {
                    scaled_gamma: (f64::from(gamma.value()) * 10_000_000.0).round() as u32,
                    inverted: true,
                };
            }
            assert_eq!(image.colour_encoding, declaration);
            assert_eq!(
                image.tone_mapping.intensity_target.to_f32(),
                [255.0, 1000.0, 10000.0, 65504.0][index % 4]
            );
            assert!(matches!(
                image.colour_encoding,
                ColourEncodingInventory::Enumerated { .. }
            ));
            check_oracles(&encoded, &expected, &case);
            check_numeric(&rig, &encoded, &[expected], &case);
            assert_eq!(encoder.in_flight_memory_stats().reserved_bytes, 0);
        }
    }
}

#[test]
fn color_animations_bind_stream_metadata_across_layout_changes_and_completion_order() {
    let rig = Rig::new();
    let extent = Extent2d::new(257, 3);
    let timing = AnimationHeader::Animation {
        ticks_per_second_numerator: std::num::NonZeroU32::new(100).unwrap(),
        ticks_per_second_denominator: std::num::NonZeroU32::new(1).unwrap(),
        num_loops: 3,
        have_timecodes: true,
    };
    for (index, transfer) in [
        TransferFunction::Srgb,
        TransferFunction::Pq,
        TransferFunction::Hlg,
        TransferFunction::Linear,
    ]
    .into_iter()
    .enumerate()
    {
        let color = spec(spaces()[index + 2], transfer);
        let case = Case {
            format: if index == 3 {
                LosslessModularFormat::Gray
            } else {
                LosslessModularFormat::Rgba
            },
            bits: [12, 31, 16, 32][index],
            kind: if index < 2 {
                SampleKind::Unsigned
            } else {
                SampleKind::Float
            },
            storage: Storage::Planar,
            reversed: true,
            byte_order: ByteOrder::Big,
            shifted: true,
        };
        let encoder = LosslessModularEncoder::with_tree_mode(rig.context.clone(), TREES[index % 2])
            .with_color_options(LosslessModularColorOptions {
                rendering_intent: INTENTS[index],
                intensity_target: FiniteF16::from_bits(0x63d0).unwrap(),
            })
            .unwrap();
        let expected = case.samples(extent);
        let input = colored(upload(&rig.context, &case, extent, &expected, 4099), color);
        let descriptor = LosslessModularAnimationDescriptor::from_pixel_format(
            extent.width,
            extent.height,
            &input.layout.format,
            timing,
        )
        .unwrap();
        let mut session = encoder.begin_animation(descriptor).unwrap();
        let mut frames = Vec::new();
        let mut jobs = Vec::new();
        for (frame, storage) in [Storage::Planar, Storage::Split, Storage::Packed]
            .into_iter()
            .enumerate()
        {
            let frame_case = Case {
                storage,
                byte_order: if frame == 1 {
                    ByteOrder::Little
                } else {
                    ByteOrder::Big
                },
                ..case
            };
            let mut expected = expected.clone();
            expected.rotate_left(frame * 3);
            let input = colored(
                upload(&rig.context, &frame_case, extent, &expected, 4099),
                color,
            );
            let mut wrong = input.clone();
            wrong.layout.format.color_spec =
                ColorSpecification::Defined(spec(ColorSpace::Bt709, TransferFunction::Linear));
            assert!(matches!(
                session.submit_frame(wrong, Default::default()),
                Err(EncodeError::InvalidConfiguration(_))
            ));
            assert_eq!(session.next_frame_index().get(), frame as u32);
            let options = FrameOptions {
                timing: FrameTiming {
                    duration_ticks: frame as u32 + 2,
                    timecode: Some(20 + frame as u32),
                },
                ..Default::default()
            };
            jobs.push(
                if frame == 2 {
                    session.submit_last_frame(input, options)
                } else {
                    session.submit_frame(input, options)
                }
                .unwrap(),
            );
            frames.push(expected);
        }
        for (index, job) in jobs.into_iter().rev().enumerate() {
            session
                .insert(if index == 1 {
                    job.wait().unwrap()
                } else {
                    pollster::block_on(job).unwrap()
                })
                .unwrap();
        }
        let encoded = session.finish_container().unwrap();
        assert_eq!(header(&encoded).animation.unwrap().num_loops, 3);
        let references: Vec<_> = frames.iter().map(Vec::as_slice).collect();
        check_frame_oracles(&encoded, &references, &case);
        check_numeric(&rig, &encoded, &frames, &case);
        assert_eq!(encoder.in_flight_memory_stats().reserved_bytes, 0);
    }
}

#[test]
fn declared_source_color_drives_requested_bradford_and_absolute_output() {
    use jxl_gpu_protocol::WhitePointAdaptation;
    use jxl_test_support::oracles::color as oracle;
    let rig = Rig::new();
    let extent = Extent2d::new(257, 3);
    let case = Case {
        format: LosslessModularFormat::Rgba,
        bits: 12,
        kind: SampleKind::Unsigned,
        storage: Storage::Planar,
        reversed: true,
        byte_order: ByteOrder::Big,
        shifted: true,
    };
    let expected = case.samples(extent);
    let encoder = LosslessModularEncoder::new(rig.context.clone());
    for (index, space) in spaces().into_iter().enumerate() {
        let transfer = [
            TransferFunction::Linear,
            TransferFunction::Srgb,
            TransferFunction::Bt709,
            TransferFunction::Dci,
            TransferFunction::Gamma(GammaExponent::new(1.0 / 2.2).unwrap()),
        ][index % 5];
        let color = spec(space, transfer);
        let input = colored(upload(&rig.context, &case, extent, &expected, 4099), color);
        let encoded = encoder.encode(input).unwrap();
        for adaptation in [WhitePointAdaptation::Bradford, WhitePointAdaptation::None] {
            let matrix = oracle::matrix_with_adaptation(
                space,
                ColorSpace::Bt709,
                adaptation == WhitePointAdaptation::Bradford,
            );
            let reference: Vec<_> = expected
                .as_chunks::<4>()
                .0
                .iter()
                .map(|pixel| {
                    let rgb = [pixel[0], pixel[1], pixel[2]].map(|value| f64::from(value) / 4095.0);
                    let rgb = oracle::convert(rgb, transfer, TransferFunction::Linear, matrix);
                    [rgb[0], rgb[1], rgb[2], f64::from(pixel[3]) / 4095.0]
                })
                .collect();
            let target = PixelFormat::rgb_f32(
                RgbChannelOrder::Rgba,
                false,
                ColorSpecification::Defined(spec(ColorSpace::Bt709, TransferFunction::Linear)),
            );
            let request = GpuOutputRequest::color(target)
                .unwrap()
                .with_alpha_output_policy(AlphaOutputPolicy::Preserve)
                .with_white_point_adaptation(adaptation);
            let mut baseline = None;
            for (decoder, fragmented) in rig.decoders.iter().zip([false, true]) {
                let mut session = if fragmented {
                    open_fragmented(decoder, &encoded, request.clone())
                } else {
                    decoder.open(&encoded, request.clone()).unwrap()
                };
                let frame = pollster::block_on(session.next_frame_async())
                    .unwrap()
                    .unwrap();
                assert!(
                    pollster::block_on(session.next_frame_async())
                        .unwrap()
                        .is_none()
                );
                drop(session);
                let actual = read(&rig.backend, &frame.output().outputs[0]);
                assert_eq!(actual.len(), reference.len() * 4);
                for (pixel, reference) in actual.as_chunks::<4>().0.iter().zip(&reference) {
                    for (&actual, &expected) in pixel.iter().zip(reference) {
                        let actual = f64::from(f32::from_bits(actual));
                        assert!(
                            (actual - expected).abs() <= 5e-6 * (1.0 + expected.abs()),
                            "{color:?} {adaptation:?}: {actual} versus {expected}"
                        );
                    }
                }
                if let Some(baseline) = &baseline {
                    assert_eq!(&actual, baseline);
                } else {
                    baseline = Some(actual);
                }
                drop(frame);
                assert_eq!(decoder.engine().in_flight_memory_stats().reserved_bytes, 0);
            }
        }
    }
}
